---
- name: "Load packages JSON content"
  ansible.builtin.slurp:
    src: "{{ local_config_root }}/nodejs/common/global-packages.json"
  register: nodejs_pkg_file_raw

- name: "Parse package JSON"
  ansible.builtin.set_fact:
    nodejs_pkg_content: "{{ nodejs_pkg_file_raw.content | b64decode | from_json }}"

- name: "Combine dependency keys (dependencies and globalPackages)"
  ansible.builtin.set_fact:
    nodejs_packages_to_install: >-
      {{ (nodejs_pkg_content.dependencies | default({}))
         | combine(nodejs_pkg_content.globalPackages | default({}))
         | dict2items | map(attribute='key') | list }}

- name: "Install global Node.js packages"
  ansible.builtin.shell:
    cmd: "source $(brew --prefix nvm)/nvm.sh && nvm use default && pnpm install -g {{ item }}@latest"
  loop: "{{ nodejs_packages_to_install }}"
  changed_when: false
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
    PNPM_HOME: "{{ ansible_env.HOME }}/Library/pnpm"
    PATH: "{{ ansible_env.HOME }}/Library/pnpm:{{ ansible_env.PATH }}"
