---
- name: "Install GitHub CLI"
  community.general.homebrew:
    name: gh
    state: present
  tags: [brew-deps]

- name: "Ensure .config/gh directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/gh"
    state: directory
    mode: "0755"

- name: "Copy gh config.yml"
  ansible.builtin.copy:
    src: "{{ role_path }}/config/common/config.yml"
    dest: "{{ ansible_env.HOME }}/.config/gh/config.yml"
    force: true
    mode: "0644"
