---
# Rust CLI tools installed from GitHub releases
#
# Each tool specifies:
#   - name: binary name (required)
#   - url: release base URL (required)
#         HTTPS (https://github.com/owner/repo) for public repos
#         SSH   (git@github.com:owner/repo)     for private repos via gh CLI
#   - tag: version tag (required)
#
# Asset naming convention: <name>-<os>-<arch>
#   os: linux, darwin
#   arch: x86_64, aarch64
tools:
  - name: gho
    url: https://github.com/akitorahayashi/gho
    tag: v0.2.0
  - name: jlo
    url: git@github.com:asterismhq/jlo
    tag: v14.0.3
  - name: kpv
    url: https://github.com/akitorahayashi/kpv
    tag: v0.6.0
  - name: mx
    url: https://github.com/akitorahayashi/mx
    tag: v2.4.0
  - name: pure
    url: https://github.com/akitorahayashi/pure
    tag: v0.6.0
  - name: ssv
    url: https://github.com/akitorahayashi/ssv
    tag: v0.2.0
