---
- name: "Set Rust version variable from file"
  ansible.builtin.slurp:
    src: "{{ local_config_root }}/rust/common/.rust-version"
  register: rust_version_file

- name: "Set Rust version fact"
  ansible.builtin.set_fact:
    rust_version: "{{ rust_version_file.content | b64decode | trim }}"

- name: "Setup Rust platform"
  ansible.builtin.include_tasks: platform.yml
  when: "'rust-platform' in ansible_run_tags"

- name: "Install cargo tools"
  ansible.builtin.include_tasks: tools.yml
  when: "'rust-tools' in ansible_run_tags"
