---
- name: "Install pyenv"
  community.general.homebrew:
    name: pyenv
    state: present
  tags: [brew-deps]

- name: "Install specified Python version with pyenv"
  ansible.builtin.command:
    cmd: "pyenv install {{ python_version }} --skip-existing"
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv/versions/{{ python_version }}"
  changed_when: false
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"

- name: "Get current global Python version"
  ansible.builtin.command:
    cmd: "pyenv global"
  register: python_current_py_global
  changed_when: false
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"

- name: "Set global Python version"
  ansible.builtin.command:
    cmd: "pyenv global {{ python_version }}"
  register: python_py_global_set
  changed_when: "python_current_py_global.stdout != python_version"
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"
