---
- name: "Ensure .config/uv directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/uv"
    state: directory
    mode: "0755"

- name: "Copy uv.toml"
  ansible.builtin.copy:
    src: "{{ role_path }}/config/common/uv.toml"
    dest: "{{ ansible_env.HOME }}/.config/uv/uv.toml"
    force: true
    mode: "0644"
