---
- name: "Install displayplacer (dependency)"
  community.general.homebrew:
    name: displayplacer
    state: present
  tags: [brew-deps]

- name: "Apply macOS system defaults"
  community.general.osx_defaults:
    domain: "{{ item.domain | default('NSGlobalDomain') }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop: "{{ lookup('file', local_config_root + '/system/common/system.yml') | from_yaml }}"
