---
- name: "Set Ruby version variable from file"
  ansible.builtin.slurp:
    src: "{{ local_config_root }}/ruby/common/.ruby-version"
  register: ruby_version_file

- name: "Set Ruby version fact"
  ansible.builtin.set_fact:
    ruby_version: "{{ ruby_version_file.content | b64decode | trim }}"

- name: "Install openssl and rbenv"
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - openssl
    - rbenv

- name: "Install specified Ruby version with rbenv"
  ansible.builtin.command:
    cmd: "rbenv install {{ ruby_version }} --skip-existing"
  args:
    creates: "{{ ansible_env.HOME }}/.rbenv/versions/{{ ruby_version }}"
  changed_when: false
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"

- name: "Set global Ruby version"
  ansible.builtin.command:
    cmd: "rbenv global {{ ruby_version }}"
  changed_when: false
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"

- name: "Install bundler gem (version 2.5.22)"
  ansible.builtin.command:
    cmd: "gem install bundler -v 2.5.22 --no-document"
  changed_when: false
  environment:
    PATH: "{{ ansible_env.HOME }}/.rbenv/shims:/opt/homebrew/bin:{{ ansible_env.PATH }}"
