---
# Cargo tools to install
# Each tool can specify:
#   - name: crate/binary name (required)
#   - git: Git repository URL (optional, omit for crates.io)
#   - tag: Git tag (optional, requires git)
#   - options: additional cargo install flags (optional)
tools:
  - name: kpv
    git: git@github.com:akitorahayashi/kpv.git
    tag: v0.4.0
  - name: mms
    git: git@github.com:akitorahayashi/mms.git
    tag: v0.2.0
  - name: pure
    git: git@github.com:akitorahayashi/pure.git
    tag: v0.5.0
  - name: fusion
    git: git@github.com:akitorahayashi/fusion.git
    tag: v1.4.0
  - name: mix
    git: git@github.com:akitorahayashi/mix.git
    tag: v1.0.0
  - name: tls
    git: git@github.com:akitorahayashi/tls.git
    tag: v1.6.0
  - name: ssv
    git: git@github.com:akitorahayashi/ssv.git
    tag: v0.1.0
  # - name: cargo-edit
  #   options: "--locked"
