---
- name: "Install GitHub CLI"
  community.general.homebrew:
    name: gh
    state: present

- name: "Ensure .config/gh directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/gh"
    state: directory
    mode: '0755'

- name: "Symlink gh config.yml"
  ansible.builtin.file:
    src: "{{ config_dir_abs_path }}/gh/config.yml"
    dest: "{{ ansible_env.HOME }}/.config/gh/config.yml"
    state: link
    force: true