name: MacOS Environment Setup CI Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml

  setup-python:
    uses: ./.github/workflows/setup-python.yml

  setup-nodejs:
    uses: ./.github/workflows/setup-nodejs.yml

  setup-runtime:
    uses: ./.github/workflows/setup-runtime.yml

  setup-ide:
    uses: ./.github/workflows/setup-ide.yml

  setup-system:
    uses: ./.github/workflows/setup-system.yml
