name: Lint and Test

on:
  workflow_call:

jobs:
  lint-and-test:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          submodules: recursive

      - name: Setup base environment
        uses: ./.github/actions/setup-base

      - name: Install shell tools
        run: |
          uv tool install shellcheck-py==0.11.0.1
          uv tool install shfmt-py==3.12.0.2
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Setup MLX Environment
        uses: ./.github/actions/setup-mlx
        
      - name: Run tests
        run: just test

      - name: Run Linters
        run: just check
