name: Setup Python

on:
  workflow_call:

jobs:
  setup-python:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Setup base environment
        uses: ./.github/actions/setup-base

      - name: Run python-platform setup
        run: just run make python-platform 

      - name: Run uv setup
        run: just run make uv 

      - name: Run python-tools setup
        run: just run make python-tools 
        
      - name: Run aider setup
        run: just run make aider 
