name: Setup Runtime

on:
  workflow_call:

jobs:
  setup-runtime:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup base environment
        uses: ./.github/actions/setup-base

      - name: Setup ruby
        run: just run make ruby mbk

      - name: Setup rust
        run: just run make rust mbk