name: Setup Runtime

on:
  workflow_call:

jobs:
  setup-runtime:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Setup base environment
        uses: ./.github/actions/setup-base

      - name: Setup ruby
        run: just run make ruby 

      - name: Setup rust
        run: just run make rust

      - name: Setup go
        run: just run make go 