name: Setup IDE

on:
  workflow_call:

jobs:
  setup-vscode:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Setup base environment
        uses: ./.github/actions/setup-base

      - name: Setup VSCode configuration
        run: just run make vscode 

      - name: Setup Cursor configuration
        run: just run make cursor 

      - name: Setup Xcode configuration
        run: just run make xcode 
